### ISSUE TITLE
Please update the nginx.conf when we release the new docker image

### ISSUE THREAD

**Issue by tmatsuo** [viender/viender#3]
The change is available at:
https://github.com/GoogleCloudPlatform/php-docker/pull/270/files

We'll notify here once we release it. Sorry for the BC break.

**Comment by tmatsuo** [comment]
Released: https://github.com/GoogleCloudPlatform/php-docker/releases/tag/2017-05-04-10-45

**Comment by tmatsuo** [comment]
Another change is happening at:
https://github.com/GoogleCloudPlatform/php-docker/pull/285

**Comment by nugrahawahyu** [comment]
@tmatsuo thanks
